# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0003_deck_deckideograph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component', to='chinese.Ideograph')),
                ('ideograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideograph', to='chinese.Ideograph')),
            ],
        ),
    ]
